apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-web.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "demo-web.name" . }}
  ports:
  - port: 80          # El puerto que el servicio expondrá
    targetPort: 8080   # El puerto en el contenedor donde Nginx escuchará
